### ISSUE TITLE
 Why eProtect form for Credit Card (Vantiv) is not being showed?

### ISSUE THREAD

**Issue by noeli-eshopguru** [mage2pro/vantiv#4]
Hi, how are you?

Is this extension same as https://marketplace.magento.com/vantiv-payment.html?
We installed this extension to integrate Vantiv into magento 2.
For Credit Card (Vantiv) on checkout page, if we set the environment to Sandbox, we can see the eProtect form but we can't see this form in Product mode.
So I reviewed the html codes in browser inspector.

https://request.eprotect.vantivprelive.com/eProtect/payframe_dvWR6G8H2xBu22Kp_empty_api2.html

This request has not any response for form action.
That's why eProtect form for Credit Card (Vantiv) is not being showed.
Could you please help me with this issue?

Kind Regards.
Noeli

**Comment by dmitrii-fediuk** [comment]
1. My module is not the same as the module in Marketplace.
1. My module does not use eProtect.

**Comment by noeli-eshopguru** [comment]
Hi

Thanks for your answer.
If we install your extension, our site will work with Vantiv properly?

Kind Regards.
Noeli

**Comment by dmitrii-fediuk** [comment]
Yes.
My module is paid, not free.
You can buy the module's license here: [https://mage2.pro/t/3102](https://mage2.pro/t/3102).
I provide free installation service to customers and solve all problems.
You can see my Vantiv module in action on the [mineralair.com](https://mineralair.com) website.
Also, I can implement custom features (e.g., eProtect) for a separate price.
You can hire me in Upwork for it: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
Also, I have implemented **20** other ready payment modules for Magento 2: [mage2.pro/tags/payment-extension](https://mage2.pro/tags/payment-extension)
E.g. my Stripe payment module is used by 80+ stores around the world: 
- [stripe.mage2.pro/customers](https://stripe.mage2.pro/customers)
- [github.com/mage2pro/stripe](https://github.com/mage2pro/stripe)
- [mage2.pro/c/stripe](https://mage2.pro/c/stripe)
